### ISSUE TITLE
Default TensorShape too large?

### ISSUE THREAD

**Issue by mikowals** [Benny-Nottonson/betterTensor#1]
Thanks for creating and sharing this repo.  It is really helpful to think about what sort of struct can be created and what sort of benefits they have.

My initial run of `mojo tensorBenchmark.mojo` failed. It output:
```
zsh: killed     ./tensorBenchmark
```

but I think it is out of memory.  It was consuming 40GB before it borked.  It runs to completion at smaller size `[4, 4, 4, 4, 4]` so you may want to reduce the `[64, 64, 64, 64, 64]` size.  Also, I think providing an example of what the output will be in your readme would be helpful to have some idea of how long it might take to complete.

Another nit is that the filenames should be snake_case.

But I will play with this some more and confirm the memory behaviour.  It could also be given your tensor doesn't clean up the pointers that the runs in the benchmark loop are a memory leak.

**Comment by mikowals** [comment]
I think my crash is a memory leak.  If I use TensorShape `[4, 4, 4, 4, 4]` and increase the `max_runtime_secs` to 60 that causes the same crash.  Freeing the pointer at the end of customTest fixes the issue.

I now get:
```
Builtin:  10998.805999999999 ms
Custom:  73937.390666666659 ms
Speedup:  0.14875837381908871
```
I think this is because builtin Tensor has SIMD on its math ops.

**Comment by Benny-Nottonson** [comment]
Thanks Michael! This was like a 20 minute project but I intend to improve it a lot, i'll give fixing this a shot when i'm home, pretty sure I just need to free some intermediate data

**Comment by Benny-Nottonson** [comment]
Pushed some changes, let me know if that fixed it. I do think this is an issue with register_passable("trivial") and pointers, since you can't define a __del__, they aren't freed properly when removed. I think I have a workaround in mind, but it gets a little convoluted.

**Comment by Benny-Nottonson** [comment]
@mikowals I believe this issue is fixed, made it @register_passable, not trivial, del method takes care of freeing the pointer.
